// Generated by https://quicktype.io

export interface Location {
    id:             number;
    pickupAddress:  string;
    dropoffAddress: string;
    landmark:       string;
    placesId:       number;
    places:         null;
    bookingsId:     number;
    bookings:       null;
}
